//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zeus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating {0} level....
        /// </summary>
        public static string CalculationsCurrentState {
            get {
                return ResourceManager.GetString("CalculationsCurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculations ended, click OK to continue working with program.
        /// </summary>
        public static string CalculationsEndAlertDescText {
            get {
                return ResourceManager.GetString("CalculationsEndAlertDescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculations ended.
        /// </summary>
        public static string CalculationsEndText {
            get {
                return ResourceManager.GetString("CalculationsEndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        public static string ControlPanelText {
            get {
                return ResourceManager.GetString("ControlPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string DataText {
            get {
                return ResourceManager.GetString("DataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string EditCopyText {
            get {
                return ResourceManager.GetString("EditCopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string EditCutText {
            get {
                return ResourceManager.GetString("EditCutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditMenuText {
            get {
                return ResourceManager.GetString("EditMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string EditPasteText {
            get {
                return ResourceManager.GetString("EditPasteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string EditRedoText {
            get {
                return ResourceManager.GetString("EditRedoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string EditUndoText {
            get {
                return ResourceManager.GetString("EditUndoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electron Concentration.
        /// </summary>
        public static string ElectronConc {
            get {
                return ResourceManager.GetString("ElectronConc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Content.
        /// </summary>
        public static string ElementContentText {
            get {
                return ResourceManager.GetString("ElementContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements.
        /// </summary>
        public static string ElementsText {
            get {
                return ResourceManager.GetString("ElementsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string FileCloseText {
            get {
                return ResourceManager.GetString("FileCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileMenuText {
            get {
                return ResourceManager.GetString("FileMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string FileOpenText {
            get {
                return ResourceManager.GetString("FileOpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string FileSaveText {
            get {
                return ResourceManager.GetString("FileSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string FileSettingsText {
            get {
                return ResourceManager.GetString("FileSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string HelpAboutText {
            get {
                return ResourceManager.GetString("HelpAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Help.
        /// </summary>
        public static string HelpInfoText {
            get {
                return ResourceManager.GetString("HelpInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpMenuText {
            get {
                return ResourceManager.GetString("HelpMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string LatitudeText {
            get {
                return ResourceManager.GetString("LatitudeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string LaunchButtonText {
            get {
                return ResourceManager.GetString("LaunchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string LongitudeText {
            get {
                return ResourceManager.GetString("LongitudeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeus.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative Ion Concentration.
        /// </summary>
        public static string NegativeIonConc {
            get {
                return ResourceManager.GetString("NegativeIonConc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive Ion Concentration.
        /// </summary>
        public static string PositiveIonConc {
            get {
                return ResourceManager.GetString("PositiveIonConc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string ResultText {
            get {
                return ResourceManager.GetString("ResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ViewMenuText {
            get {
                return ResourceManager.GetString("ViewMenuText", resourceCulture);
            }
        }
    }
}
