//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zeus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performer: Minyaev I. D., student of CSE(b)-411.
        /// </summary>
        public static string AboutAuthorText {
            get {
                return ResourceManager.GetString("AboutAuthorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thesis of the topic &quot;Development and computer realization of mathematical model of vertical current formation between lithosphere and ionosphere of Earth&quot;.
        /// </summary>
        public static string AboutDiplomaText {
            get {
                return ResourceManager.GetString("AboutDiplomaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail: ayli.veaynim@gmail.com.
        /// </summary>
        public static string AboutEmailText {
            get {
                return ResourceManager.GetString("AboutEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Murmansk, 2015.
        /// </summary>
        public static string AboutPlaceText {
            get {
                return ResourceManager.GetString("AboutPlaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/LimeonPie/Zeus.
        /// </summary>
        public static string AboutSiteText {
            get {
                return ResourceManager.GetString("AboutSiteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor: Namgaladze A. A., professor of CSE facility.
        /// </summary>
        public static string AboutSupervisorText {
            get {
                return ResourceManager.GetString("AboutSupervisorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aerosol.
        /// </summary>
        public static string Aerosol {
            get {
                return ResourceManager.GetString("Aerosol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All charges concentrations.
        /// </summary>
        public static string AllChargesConc {
            get {
                return ResourceManager.GetString("AllChargesConc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AllChargesText {
            get {
                return ResourceManager.GetString("AllChargesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating {0} level....
        /// </summary>
        public static string CalculationsCurrentState {
            get {
                return ResourceManager.GetString("CalculationsCurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculations ended, click OK to continue working with program.
        /// </summary>
        public static string CalculationsEndAlertDescText {
            get {
                return ResourceManager.GetString("CalculationsEndAlertDescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculations ended.
        /// </summary>
        public static string CalculationsEndText {
            get {
                return ResourceManager.GetString("CalculationsEndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentration.
        /// </summary>
        public static string Concentration {
            get {
                return ResourceManager.GetString("Concentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        public static string ControlPanelText {
            get {
                return ResourceManager.GetString("ControlPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string DataText {
            get {
                return ResourceManager.GetString("DataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string EditCopyText {
            get {
                return ResourceManager.GetString("EditCopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string EditCutText {
            get {
                return ResourceManager.GetString("EditCutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditMenuText {
            get {
                return ResourceManager.GetString("EditMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string EditPasteText {
            get {
                return ResourceManager.GetString("EditPasteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string EditRedoText {
            get {
                return ResourceManager.GetString("EditRedoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string EditUndoText {
            get {
                return ResourceManager.GetString("EditUndoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity.
        /// </summary>
        public static string Electricity {
            get {
                return ResourceManager.GetString("Electricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electron Concentration.
        /// </summary>
        public static string ElectronConc {
            get {
                return ResourceManager.GetString("ElectronConc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electron.
        /// </summary>
        public static string ElectronConcShort {
            get {
                return ResourceManager.GetString("ElectronConcShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E velocity.
        /// </summary>
        public static string ElectronVelocity {
            get {
                return ResourceManager.GetString("ElectronVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Content.
        /// </summary>
        public static string ElementContentText {
            get {
                return ResourceManager.GetString("ElementContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements.
        /// </summary>
        public static string ElementsText {
            get {
                return ResourceManager.GetString("ElementsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flux.
        /// </summary>
        public static string EternityFlux {
            get {
                return ResourceManager.GetString("EternityFlux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string FileCloseText {
            get {
                return ResourceManager.GetString("FileCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileMenuText {
            get {
                return ResourceManager.GetString("FileMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string FileOpenText {
            get {
                return ResourceManager.GetString("FileOpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string FileSaveText {
            get {
                return ResourceManager.GetString("FileSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string FileSettingsText {
            get {
                return ResourceManager.GetString("FileSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid step.
        /// </summary>
        public static string GridStep {
            get {
                return ResourceManager.GetString("GridStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string HelpAboutText {
            get {
                return ResourceManager.GetString("HelpAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Help.
        /// </summary>
        public static string HelpInfoText {
            get {
                return ResourceManager.GetString("HelpInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpMenuText {
            get {
                return ResourceManager.GetString("HelpMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I- velocity.
        /// </summary>
        public static string IonMinusVelocity {
            get {
                return ResourceManager.GetString("IonMinusVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I+ velocity.
        /// </summary>
        public static string IonPlusVelocity {
            get {
                return ResourceManager.GetString("IonPlusVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string LatitudeText {
            get {
                return ResourceManager.GetString("LatitudeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string LaunchButtonText {
            get {
                return ResourceManager.GetString("LaunchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LogPlotMode {
            get {
                return ResourceManager.GetString("LogPlotMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string LongitudeText {
            get {
                return ResourceManager.GetString("LongitudeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeus.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative Ion Concentration.
        /// </summary>
        public static string NegativeIonConc {
            get {
                return ResourceManager.GetString("NegativeIonConc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ion-.
        /// </summary>
        public static string NegativeIonShort {
            get {
                return ResourceManager.GetString("NegativeIonShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitrogen.
        /// </summary>
        public static string Nitrogen {
            get {
                return ResourceManager.GetString("Nitrogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string NormalPlotMode {
            get {
                return ResourceManager.GetString("NormalPlotMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive Ion Concentration.
        /// </summary>
        public static string PositiveIonConc {
            get {
                return ResourceManager.GetString("PositiveIonConc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ion+.
        /// </summary>
        public static string PositiveIonShort {
            get {
                return ResourceManager.GetString("PositiveIonShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redraw.
        /// </summary>
        public static string Redraw {
            get {
                return ResourceManager.GetString("Redraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string ResultText {
            get {
                return ResourceManager.GetString("ResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has been succesfully saved.
        /// </summary>
        public static string SaveStatusSucces {
            get {
                return ResourceManager.GetString("SaveStatusSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Distribution.
        /// </summary>
        public static string TemperatureDistribution {
            get {
                return ResourceManager.GetString("TemperatureDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time interval.
        /// </summary>
        public static string TimeInterval {
            get {
                return ResourceManager.GetString("TimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        public static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ViewMenuText {
            get {
                return ResourceManager.GetString("ViewMenuText", resourceCulture);
            }
        }
    }
}
